yetiforce:
  build: 3.1.0
  ports:
    - "80:80"
  links:
    - "db"
  environment:
    DB_TYPE: mysql
    DB_MANAGER: MysqlManager
dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql
db:
  image: mysql:5.6
  volumes_from:
    - dbdata
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: yetiforcedb
    MYSQL_USER: yetiforceuser
    MYSQL_PASSWORD: yetiforcepass